# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    
    # Enable logs for production environment!
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            whisky_tango_foxtrot

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    # Getting project:disable to work
    check_lock:             true
    
    # Spanish language supported, but it's not the default anymore
    default_culture:        en
    i18n:                   true
    
    # Uncomment if you will use sfGuardPlugin
    #login_module:           sfGuardAuth
    #login_action:           signin

    #secure_module:          sfGuardAuth
    #secure_action:          secure