propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  categoria:
    _attributes: { phpName: Categoria, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    descripcion_categoria: { phpName: DescripcionCategoria, type: VARCHAR, size: '40', required: true }
    edad_min: { phpName: EdadMin, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    edad_max: { phpName: EdadMax, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
  club:
    _attributes: { phpName: Club, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    nombre_club: { phpName: NombreClub, type: VARCHAR, size: '45', required: true }
  direccion:
    _attributes: { phpName: Direccion, idMethod: native }
    persona_nro_doc: { phpName: PersonaNroDoc, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: persona, foreignReference: nro_doc, onDelete: CASCADE, onUpdate: CASCADE }
    calle: { phpName: Calle, type: VARCHAR, size: '45', primaryKey: true, required: true, defaultValue: 'Sin Nombre' }
    numero: { phpName: Numero, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, defaultValue: '0' }
    monoblock_edif: { phpName: MonoblockEdif, type: VARCHAR, size: '5', required: false, defaultValue: S/N }
    piso: { phpName: Piso, type: VARCHAR, size: '3', required: false, defaultValue: S/N }
    dpto: { phpName: Dpto, type: VARCHAR, size: '3', required: false, defaultValue: S/N }
    _indexes: { fk_direccion_persona1: [persona_nro_doc] }
  inscripto:
    _attributes: { phpName: Inscripto, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    persona_nro_doc: { phpName: PersonaNroDoc, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: persona, foreignReference: nro_doc }
    torneo_cat_id: { phpName: TorneoCatId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: torneo_categoria, foreignReference: id_torneo_categoria }
    nro_equipo: { phpName: NroEquipo, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '0' }
    club_representado: { phpName: ClubRepresentado, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: club, foreignReference: id }
    _indexes: { fk_inscripto_Club1: [club_representado], fk_inscripto_torneo_categoria1: [torneo_cat_id], fk_inscripto_persona1: [persona_nro_doc] }
    _uniques: { torneo_cat_id_UNIQUE: [torneo_cat_id, persona_nro_doc] }
  localidad:
    _attributes: { phpName: Localidad, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    nombre_loc: { phpName: NombreLoc, type: VARCHAR, size: '40', required: true }
    cod_postal: { phpName: CodPostal, type: VARCHAR, size: '10', required: true }
    provincia_id: { phpName: ProvinciaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: provincia, foreignReference: id }
    _indexes: { fk_LOCALIDAD_PROVINCIA: [provincia_id] }
  pedido:
    _attributes: { phpName: Pedido, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    proveedor_id: { phpName: ProveedorId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: proveedor, foreignReference: id }
    fecha_pedido: { phpName: FechaPedido, type: TIMESTAMP, required: true, defaultExpr: CURRENT_TIMESTAMP }
    estado: { phpName: Estado, type: BOOLEAN, size: '1', required: true, defaultValue: false }
    _indexes: { fk_pedido_proveedor1: [proveedor_id] }
  pedido_producto:
    _attributes: { phpName: PedidoProducto, idMethod: native }
    pedido_id: { phpName: PedidoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: pedido, foreignReference: id }
    producto_id: { phpName: ProductoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: producto, foreignReference: id }
    _indexes: { fk_pedido_producto_producto1: [producto_id] }
  persona:
    _attributes: { phpName: Persona, idMethod: native }
    nro_doc: { phpName: NroDoc, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, defaultValue: '0' }
    nom_apellido: { phpName: NomApellido, type: VARCHAR, size: '45', required: true }
    apellido: { phpName: Apellido, type: VARCHAR, size: '45', required: true }
    fecha_nacimiento: { phpName: FechaNacimiento, type: DATE, required: true }
    e_mail: { phpName: EMail, type: VARCHAR, size: '30', required: false }
    localidad_id: { phpName: LocalidadId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: localidad, foreignReference: id }
    _indexes: { fk_PERS_LOCALIDAD: [localidad_id] }
  producto:
    _attributes: { phpName: Producto, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    descripcion_prod: { phpName: DescripcionProd, type: VARCHAR, size: '45', required: true }
    marca: { phpName: Marca, type: VARCHAR, size: '45', required: true }
    presentacion: { phpName: Presentacion, type: VARCHAR, size: '45', required: true }
    precio: { phpName: Precio, type: DECIMAL, size: '6', scale: '2', sqlType: 'decimal(6,2) unsigned', required: true }
  proveedor:
    _attributes: { phpName: Proveedor, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    nombre_proveedor: { phpName: NombreProveedor, type: VARCHAR, size: '45', required: true }
    dom_calle: { phpName: DomCalle, type: VARCHAR, size: '45', required: false }
    dom_nro: { phpName: DomNro, type: VARCHAR, size: '10', required: false }
    dom_piso: { phpName: DomPiso, type: VARCHAR, size: '10', required: false }
    dom_dpto: { phpName: DomDpto, type: VARCHAR, size: '10', required: false }
    telefono: { phpName: Telefono, type: VARCHAR, size: '20', required: true }
  provincia:
    _attributes: { phpName: Provincia, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    nombre_prov: { phpName: NombreProv, type: VARCHAR, size: '40', required: true }
  puntos_puesto:
    _attributes: { phpName: PuntosPuesto, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    puesto: { phpName: Puesto, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, index: unique }
    puntos_por_puesto: { phpName: PuntosPorPuesto, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
  ranking:
    _attributes: { phpName: Ranking, idMethod: native }
    pelotari_nro_doc: { phpName: PelotariNroDoc, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: inscripto, foreignReference: persona_nro_doc }
    tipo_ranking: { phpName: TipoRanking, type: BOOLEAN, size: '1', primaryKey: true, required: true, defaultValue: false }
    categoria_id: { phpName: CategoriaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, defaultValue: '0', foreignTable: categoria, foreignReference: id }
    pelotari_puntos: { phpName: PelotariPuntos, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    _indexes: { fk_ranking_categoria1: [categoria_id], fk_ranking_inscripto1: [pelotari_nro_doc] }
  reserva:
    _attributes: { phpName: Reserva, idMethod: native }
    socio_nro_doc: { phpName: SocioNroDoc, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, defaultValue: '0', foreignTable: socio, foreignReference: persona_nro_doc, onDelete: CASCADE, onUpdate: CASCADE }
    tipo_reserva_id: { phpName: TipoReservaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, defaultValue: '0', foreignTable: tipo_reserva, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    dia_comienzo_reserva: { phpName: DiaComienzoReserva, type: DATE, primaryKey: true, required: true, defaultValue: '0000-00-00' }
    hora_comienzo_reserva: { phpName: HoraComienzoReserva, type: TIME, primaryKey: true, required: true, defaultValue: '00:00:00' }
    dia_fin_reserva: { phpName: DiaFinReserva, type: DATE, required: false }
    hora_fin_reserva: { phpName: HoraFinReserva, type: TIME, required: false }
    cantidad_turnos: { phpName: CantidadTurnos, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '1' }
    estado: { phpName: Estado, type: BOOLEAN, size: '1', required: true, defaultValue: false }
    _indexes: { fk_reserva_socio: [socio_nro_doc], fk_reserva_tipo_reserva: [tipo_reserva_id] }
  resultado_torneo:
    _attributes: { phpName: ResultadoTorneo, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    puesto_id: { phpName: PuestoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: puntos_puesto, foreignReference: id }
    torneo_cat_id: { phpName: TorneoCatId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: torneo_categoria, foreignReference: id_torneo_categoria }
    pelotari_nro_doc: { phpName: PelotariNroDoc, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: inscripto, foreignReference: persona_nro_doc }
    _indexes: { fk_Resultado_torneo_inscripto1: [pelotari_nro_doc], fk_Resultado_torneo_torneo_categoria1: [torneo_cat_id], fk_Resultado_torneo_puntos_puesto1: [puesto_id] }
  socio:
    _attributes: { phpName: Socio, idMethod: native }
    persona_nro_doc: { phpName: PersonaNroDoc, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, defaultValue: '0', foreignTable: persona, foreignReference: nro_doc, onDelete: CASCADE, onUpdate: CASCADE }
    fecha_alta: { phpName: FechaAlta, type: DATE, required: true }
    vitalicio: { phpName: Vitalicio, type: BOOLEAN, size: '1', required: true, defaultValue: false }
    activo: { phpName: Activo, type: BOOLEAN, size: '1', required: true, defaultValue: false }
    _indexes: { fk_socio_persona: [persona_nro_doc] }
  stock:
    _attributes: { phpName: Stock, idMethod: native }
    producto_id: { phpName: ProductoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: producto, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    cantidad_actual: { phpName: CantidadActual, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '0' }
    cantidad_minima: { phpName: CantidadMinima, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, defaultValue: '0' }
    _indexes: { fk_STOCK_PRODUCTO1: [producto_id] }
  telefono:
    _attributes: { phpName: Telefono, idMethod: native }
    persona_nro_doc: { phpName: PersonaNroDoc, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, required: true, foreignTable: persona, foreignReference: nro_doc, onDelete: CASCADE, onUpdate: CASCADE }
    telefono_nro: { phpName: TelefonoNro, type: VARCHAR, size: '20', primaryKey: true, required: true, defaultValue: S/N }
    _indexes: { fk_telefono_persona1: [persona_nro_doc] }
  tipo_reserva:
    _attributes: { phpName: TipoReserva, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    descirpcion_reserva: { phpName: DescirpcionReserva, type: VARCHAR, size: '45', required: true }
    tiempo_reserva: { phpName: TiempoReserva, type: DECIMAL, scale: '0', required: true }
    coste: { phpName: Coste, type: DECIMAL, scale: '0', sqlType: 'decimal(10,0) unsigned', required: true }
  torneo:
    _attributes: { phpName: Torneo, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    anio: { phpName: Anio, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true }
    nombre: { phpName: Nombre, type: VARCHAR, size: '45', required: true }
    tipo_torneo: { phpName: TipoTorneo, type: BOOLEAN, size: '1', required: true }
  torneo_categoria:
    _attributes: { phpName: TorneoCategoria, idMethod: native }
    id_torneo_categoria: { phpName: IdTorneoCategoria, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    torneo_id: { phpName: TorneoId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: torneo, foreignReference: id }
    categoria_id: { phpName: CategoriaId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: true, foreignTable: categoria, foreignReference: id }
    _indexes: { fk_torneo_categoria_torneo1: [torneo_id], fk_torneo_categoria_CATEGORIA1: [categoria_id] }
