propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
    
  localidad:
    nombre_loc: { primaryString: true }
    
  tipo_reserva:
    descirpcion_reserva: { primaryString: true }
    
  producto:
    descripcion_prod: { primaryString: true }
  
  pedido_producto:
    _attributes: { isCrossRef: true }
    
  torneo:
    nombre: { primaryString: true }
    
  categoria:
    descripcion_categoria: { primaryString: true }
    
  persona:
    nro_doc: { primaryString: true }

  torneo_categoria:
    id_torneo_categoria: { primaryString: true }
    torneo_id: { primaryString: true }
    
  club:
    nombre_club: { primaryString: true }
    
  proveedor:
    nombre_proveedor: { primaryString: true }
    
  pedido:
    id: { primaryString: true }
